/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ResidentialHouse.glb --types 
Files: ResidentialHouse.glb [210KB]
Model: "Residential Houses" from: https://www.sloyd.ai/ 
*/
import { BaseHome } from './BaseHome';
import { Floor } from './Floor';
import { Roof } from './Roof';
import { useResidentialHouse } from './useResidentialHouse';

type Props = JSX.IntrinsicElements['group'] & { displayAxesHelper?: boolean };

export const ResidentialHouse = ({
  displayAxesHelper = false,
  ...props
}: Props): JSX.Element => {
  const { nodes, materials } = useResidentialHouse();

  return (
    <group {...props} dispose={null}>
      {displayAxesHelper && <axesHelper args={[50]} />}
      <BaseHome nodes={nodes} materials={materials} />
      <Roof nodes={nodes} materials={materials} />
      <Floor nodes={nodes} materials={materials} />
    </group>
  );
};
