/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ResidentialHouse.glb --types 
Files: ResidentialHouse.glb [210KB]
Model: "Residential Houses" from: https://www.sloyd.ai/ 
*/
import { BaseHome } from './BaseHome';
import { Floor } from './Floor';
import { Roof } from './Roof';
import { useResidentialHouse } from './useResidentialHouse';

type Props = JSX.IntrinsicElements['group'] & {
  nFloors?: number;
  displayAxesHelper?: boolean;
};

export const ResidentialHouse = ({
  nFloors = 1,
  displayAxesHelper = false,
  ...props
}: Props): JSX.Element => {
  const { nodes, materials } = useResidentialHouse();

  return (
    <group {...props} dispose={null}>
      {displayAxesHelper && <axesHelper args={[50]} />}
      <Roof nodes={nodes} materials={materials} nFloors={nFloors} />
      {[...Array.from(Array(nFloors))].map((_, i) => (
        <Floor key={i} nodes={nodes} materials={materials} floor={i} />
      ))}
      <BaseHome nodes={nodes} materials={materials} />
    </group>
  );
};
