/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 OriginalFirTree.glb --transform --types 
Files: OriginalFirTree.glb [129.38KB] > FirTree.glb [13.98KB] (89%)
Model: "Trees" from: https://www.sloyd.ai/ 
*/
import { GroupProps } from '@react-three/fiber';

import { useFirTree } from './useFirTree';

type Props = GroupProps;

export const FirTree = (props: Props): JSX.Element => {
  const { nodes, materials } = useFirTree();

  /**
   * This code has been generated with the command `npx gltfjsx`.
   * See the dedicated chapter in the README to learn more.
   */
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Extrusion_Spline.geometry}
        material={materials.Spine}
        position={[0, 3.015, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Trunk_Extrusion_Spline.geometry}
        material={materials.Trunk}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};
